version: '2.34.0'

services:
  go-moderation-service:
    container_name: go-moderation-service
    image: souravprasadas/go-moderation-service:1.0.0
    environment:
      - SERVER_PORT=8080
      - SERVER_PORT=8080
      - SERVER_DEBUG=false
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=databasepasswd
      - DB_NAME=moderation_service
      - SECRET_KEY=falkdsfjlksa
      - SENDGRID_API_KEY=fjlskfdjlsa
      - SENDGRID_FROM_EMAIL_ADDRESS=sender@gmail.com
      - GCP_CREDENTIALS_FILE=gcp_credentials_file.json
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgresql
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=databasepasswd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=moderation_service
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}